services:
  - type: web
    name: vahansetu
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --pythonpath vahansetu app:app
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
